{% set name = "pygraphviz" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # For some reason there are no .gz files here
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: a7bec6609f37cf1e64898c59f075afd659106cf9356c5f387cecaa2e0cdb2304
  patches:
    # - 0001-Merge-bytes-decoding-fix.patch
    # - 0002-Fix-segmentation-faults-in-test_clear.py.patch
    # - 0003-Prevent-STARTUPINFO-persistence-between-calls.patch  # [win]

build:
  number: 1
  # It is possible to add windows support, but the
  # graphviz win package is not ready for it yet
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - graphviz

  build:
    - {{ compiler('c') }}
    - pkg-config
  run:
    - python
    - graphviz

test:
  imports:
    - pygraphviz
    - pygraphviz.tests
  source_files:
    - pygraphviz/tests
  commands:
    - pytest --doctest-modules --durations=10 --pyargs pygraphviz
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  requires:
    - pytest

about:
  home: http://pygraphviz.github.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to Graphviz
  description: |
      PyGraphviz is a Python interface to the Graphviz graph layout and
      visualization package. With PyGraphviz you can create, edit, read, write,
      and draw graphs using Python to access the Graphviz graph data structure
      and layout algorithms. PyGraphviz provides a similar programming
      interface to NetworkX (http://networkx.github.io).
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/pygraphviz/pygraphviz

extra:
  recipe-maintainers:
    - nehaljwani
