{% set name = "pygraphviz" %}
{% set version = "1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # For some reason there are no .gz files here
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: fa18f7c6cea28341a4e466ed0cf05682b0a68288afe8dd7c9426782f7c1ae01c
  patches:
    - patches/0001-Ensure-define_macros-remains-a-list-on-Windows.patch
    - patches/0002-AGraph-Don-t-leak-file-descriptor-on-read-path.patch

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - graphviz
    - setuptools
    - wheel
  run:
    - python
    - graphviz

test:
  imports:
    - pygraphviz
    - pygraphviz.tests
  source_files:
    - pygraphviz/tests
  commands:
    - pytest --doctest-modules --durations=10 --pyargs pygraphviz
  requires:
    - pytest

about:
  home: https://pygraphviz.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to Graphviz
  description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and
    visualization package. With PyGraphviz you can create, edit, read, write,
    and draw graphs using Python to access the Graphviz graph data structure
    and layout algorithms. PyGraphviz provides a similar programming
    interface to NetworkX (https://networkx.github.io).
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/pygraphviz/pygraphviz

extra:
  recipe-maintainers:
    - nehaljwani
