{% set name = "pygraphviz" %}
{% set version = "1.14" %}
{% set sha256 = "c10df02377f4e39b00ae17c862f4ee7e5767317f1c6b2dfd04cea6acc7fc2bea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # For some reason there are no .gz files here
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygraphviz-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - graphviz
    - setuptools
    - wheel
  run:
    - python
    # https://github.com/pygraphviz/pygraphviz/blob/pygraphviz-1.14/INSTALL.txt#L8
    - graphviz >=2.46,<3

test:
  imports:
    - pygraphviz
    - pygraphviz.tests
  source_files:
    - pygraphviz/tests
  commands:
    - pip check
    - pytest --doctest-modules --durations=10 --pyargs pygraphviz
  requires:
    - pip
    - pytest

about:
  home: https://pygraphviz.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to Graphviz
  description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and
    visualization package. With PyGraphviz you can create, edit, read, write,
    and draw graphs using Python to access the Graphviz graph data structure
    and layout algorithms. PyGraphviz provides a similar programming
    interface to NetworkX (https://networkx.github.io).
  doc_url: https://pygraphviz.github.io/documentation/latest/
  dev_url: https://github.com/pygraphviz/pygraphviz

extra:
  recipe-maintainers:
    - nehaljwani
