travis:
  secure:
    BINSTAR_TOKEN: It6Mb9XkXhexqeWwr2lnd/dZ16qNARxAZiBsb1KkTnsSoglYSQa852hwSATW9SFgwlBjJ2ZdUdhnlHSwQLMi5aM7Zrl85eG8iLDAQNk+6VcAUq+O+ZG4h7wAUOT/MC7oZpnHQ+JUsDeBXT8UPZtqFz/7lYsfJzcrq1FZ0XgwK4R32+aZ4mwBCqrCc4cNkpNqgEWhNr4iTtnCJPZ4NpkFhuKhxyLZqwQk1UpZNK6qEfa7RZwZVMc4nUf/bBeNpCGmg4TmWoUiCtdGof7tR5aNHNoxGjtJeP5+VTNYf+QticVCko3mgmiKVSgRHWykD9hj4dOhLuvFKkuGweMOhPxWRRma23NrBUT0lxYUlJOghtUwPVv0l4ayGy7aZzySbOHmod7VOrenUlq1twdpU2fja/9TN7s6lHQ6UD7u+oDjRJMQK+8b/JHhObtdCLtynbTujtjrYLnxtPIDxyd9JdTTLS5PgVcH9yoifGscwRLqmXRAhxsky8vnuee1q0N7vXFiymWGG7sbswWhNY9Zkl4XDMXo/0TpIkT2clX89ZyTXJs3dx4tJA4PqPK/fJZipyKilM1Q/6mcsts2DFc8+hR0/b6CU5LwcnEBJ9ap6/PM5rlt2vHxXhmuuo1NnCAudDDZECh5AMwJjIakY2s04+m95rv9nNYpFvq1VZeVeYzIn4s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
